import { Providers } from "@/core/components/providers/providers";
import type { Metadata } from "next";
import { Dancing_Script, Geist, Geist_Mono } from "next/font/google";
import { PropsWithChildren } from "react";

import { Footer } from "@/features/marketing/components/footer";
import { Header } from "@/features/marketing/components/header";
import "./globals.css";

const geist = Geist({ subsets: ["latin"], variable: "--font-sans" });
const geistMono = Geist_Mono({ subsets: ["latin"], variable: "--font-mono" });
const dancingScript = Dancing_Script({ subsets: ["latin"], variable: "--font-dancing-script" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<PropsWithChildren>) {
  return (
    <html lang="fr" suppressHydrationWarning>
      <body
        className={`${geist.className} ${geistMono.variable} ${dancingScript.variable} antialiased`}
        id="home"
      >
        <Providers>
          <Header />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
